apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    targetRevision: main
    path: charts/prometheus-alertmanager
    helm:
      values: |
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              receiver: 'slack-notifications'
            receivers:
              - name: 'slack-notifications'
                slack_configs:
                  - send_resolved: true
                    channel: '#alerts'
                    api_url: 'https://hooks.slack.com/services/XXXXX/YYYYY/ZZZZZ'
  project: default

