apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/alloy/alloy-helm'
    targetRevision: main
    path: charts/alloy
  project: default
