apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beyla
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/beyla/beyla-helm'
    targetRevision: main
    path: charts/beyla
  project: default
