apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/grafana/helm-charts'
    targetRevision: main
    path: charts/tempo
    helm:
      values: |
        tempo:
          allInOne:
            enabled: true
  project: default
